import type { CollectionConfig } from 'payload'

import { fileMetadataField } from '@/fields'
import { GENDER_OPTIONS } from '@/lib/utilities/gender'
import { restrictUploadToAdmin } from '@/plugins/access'
import {
  hlsUrlField,
  mixedMediaUrlField,
  mp4UrlField,
  previewUrlField,
} from '@/plugins/storage/urlFields'

import { framesByNarrator } from './endpoints/byNarrator'
import { cascadeFrameNodeChange } from './hooks/cascadeFrameNodeChange'

export const Frames: CollectionConfig = {
  labels: {
    plural: 'Meditation Frames',
    singular: 'Meditation Frame',
  },
  slug: 'frames',
  indexes: [
    {
      fields: ['imageSet'],
    },
  ],
  endpoints: [framesByNarrator],
  hooks: {
    beforeChange: [restrictUploadToAdmin({ label: 'frame file' })],
    afterChange: [cascadeFrameNodeChange],
  },
  upload: {
    staticDir: 'media/frames',
    mimeTypes: [
      // Images
      'image/jpeg',
      'image/jpg',
      'image/png',
      'image/webp',
      // Videos
      'video/mp4',
      'video/webm',
    ],
    // imageSizes removed - using Cloudflare Images flexible variants and Stream thumbnails
  },
  admin: {
    group: 'Media',
    useAsTitle: 'filename',
    defaultColumns: ['subtleSystemNode', 'tags', 'previewUrl', 'imageSet'],
    groupBy: true,
  },
  fields: [
    // Virtual URL fields generated by factory functions
    // url: MP4/image/file URL (mixed-media), hlsUrl: HLS manifest (videos),
    // mp4Url: MP4 download (videos), previewUrl: thumbnail
    mixedMediaUrlField({ collection: 'frames' }),
    hlsUrlField({ collection: 'frames' }),
    mp4UrlField({ collection: 'frames' }),
    previewUrlField({ collection: 'frames' }),
    {
      name: 'imageSet',
      type: 'select',
      options: GENDER_OPTIONS,
      required: true,
    },
    // Optional: a null `subtleSystemNode` is the "Other" bucket for frames
    // that don't depict a specific chakra/nadi (e.g. bandhan, namaste). The
    // legacy `category` enum was required, but its value space mixed chakras
    // with non-chakra ritual gestures; splitting non-chakra values into `tags`
    // means the relationship genuinely doesn't apply to every frame.
    {
      type: 'row',
      fields: [
        {
          name: 'subtleSystemNode',
          type: 'relationship',
          relationTo: 'subtle-system-nodes',
          hasMany: false,
          admin: {
            description:
              'Which chakra or nadi this frame depicts. Leave blank for "Other" frames (e.g. bandhan, namaste) — use the tags field for those instead.',
          },
        },
        {
          name: 'label',
          type: 'text',
          required: true,
          admin: {
            description:
              'Human-readable name for "Other" frames (bandhan, namaste, etc.) that have no chakra/nadi node.',
            condition: (_, siblingData) => !siblingData?.subtleSystemNode,
          },
        },
      ],
    },
    {
      name: 'tags',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Anahat', value: 'anahat' },
        { label: 'Back', value: 'back' },
        { label: 'Bandhan', value: 'bandhan' },
        { label: 'Both Hands', value: 'both hands' },
        { label: 'Center', value: 'center' },
        { label: 'Channel', value: 'channel' },
        { label: 'Clearing', value: 'clearing' },
        { label: 'Earth', value: 'earth' },
        { label: 'Ego', value: 'ego' },
        { label: 'Feel', value: 'feel' },
        { label: 'Ham Ksham', value: 'ham ksham' },
        { label: 'Hamsa', value: 'hamsa' },
        { label: 'Hand', value: 'hand' },
        { label: 'Hands', value: 'hands' },
        { label: 'Left', value: 'left' },
        { label: 'Left Handed', value: 'lefthanded' },
        { label: 'Massage', value: 'massage' },
        { label: 'Meditate', value: 'meditate' },
        { label: 'Namaste', value: 'namaste' },
        { label: 'Raise', value: 'raise' },
        { label: 'Ready', value: 'ready' },
        { label: 'Right', value: 'right' },
        { label: 'Right Handed', value: 'righthanded' },
        { label: 'Rising', value: 'rising' },
        { label: 'Silent', value: 'silent' },
        { label: 'Superego', value: 'superego' },
        { label: 'Tapping', value: 'tapping' },
      ],
    },
    {
      // Removed: thumbnail FileAttachmentField (replaced by thumbnailUrl virtual field from Cloudflare Stream)
      name: 'duration',
      type: 'number',
      hooks: {
        afterRead: [
          async ({ data }) => {
            return data &&
              typeof data.fileMetadata === 'object' &&
              typeof data.fileMetadata.duration === 'number'
              ? Math.round(data.fileMetadata.duration)
              : undefined
          },
        ],
      },
    },
    fileMetadataField(),
  ],
}
