/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    clients: ClientAuthOperations;
  };
  blocks: {};
  collections: {
    meditations: Meditation;
    music: Music;
    frames: Frame;
    media: Media;
    narrators: Narrator;
    'media-tags': MediaTag;
    'meditation-tags': MeditationTag;
    'music-tags': MusicTag;
    users: User;
    clients: Client;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'media-tags': {
      media: 'media';
    };
    'meditation-tags': {
      meditations: 'meditations';
    };
    'music-tags': {
      music: 'music';
    };
  };
  collectionsSelect: {
    meditations: MeditationsSelect<false> | MeditationsSelect<true>;
    music: MusicSelect<false> | MusicSelect<true>;
    frames: FramesSelect<false> | FramesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    narrators: NarratorsSelect<false> | NarratorsSelect<true>;
    'media-tags': MediaTagsSelect<false> | MediaTagsSelect<true>;
    'meditation-tags': MeditationTagsSelect<false> | MeditationTagsSelect<true>;
    'music-tags': MusicTagsSelect<false> | MusicTagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'cs';
  user:
    | (User & {
        collection: 'users';
      })
    | (Client & {
        collection: 'clients';
      });
  jobs: {
    tasks: {
      resetClientUsage: TaskResetClientUsage;
      trackClientUsage: TaskTrackClientUsage;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ClientAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditations".
 */
export interface Meditation {
  id: string;
  title: string;
  locale: 'en' | 'cs';
  publishAt?: string | null;
  slug?: string | null;
  thumbnail: string | Media;
  /**
   * Duration in seconds
   */
  duration?: number | null;
  narrator: string | Narrator;
  tags?: (string | MeditationTag)[] | null;
  /**
   * Music with this tag will be offered to the seeker
   */
  musicTag?: (string | null) | MusicTag;
  /**
   * Frames associated with this meditation with audio-synchronized editing
   */
  frames?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  frameData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Tags to categorize this image
   */
  tags?: (string | MediaTag)[] | null;
  /**
   * Attribution or copyright information
   */
  credit?: string | null;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-tags".
 */
export interface MediaTag {
  id: string;
  name: string;
  media?: {
    docs?: (string | Media)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrators".
 */
export interface Narrator {
  id: string;
  name: string;
  gender: 'male' | 'female';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditation-tags".
 */
export interface MeditationTag {
  id: string;
  /**
   * This label will be used in the editor
   */
  name: string;
  /**
   * This localized title will be shown to public users
   */
  title: string;
  meditations?: {
    docs?: (string | Meditation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-tags".
 */
export interface MusicTag {
  id: string;
  /**
   * This label will be used in the editor
   */
  name: string;
  /**
   * This localized title will be shown to public users
   */
  title: string;
  music?: {
    docs?: (string | Music)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music".
 */
export interface Music {
  id: string;
  title: string;
  slug?: string | null;
  tags?: (string | MusicTag)[] | null;
  /**
   * Attribution or credit information
   */
  credit?: string | null;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frames".
 */
export interface Frame {
  id: string;
  preview?: string | null;
  imageSet: 'male' | 'female';
  category:
    | 'mooladhara'
    | 'swadhistan'
    | 'nabhi'
    | 'void'
    | 'anahat'
    | 'vishuddhi'
    | 'agnya'
    | 'sahasrara'
    | 'clearing'
    | 'kundalini'
    | 'meditate'
    | 'ready'
    | 'namaste';
  tags?:
    | (
        | 'anahat'
        | 'back'
        | 'bandhan'
        | 'both hands'
        | 'center'
        | 'channel'
        | 'earth'
        | 'ego'
        | 'feel'
        | 'ham ksham'
        | 'hamsa'
        | 'hand'
        | 'hands'
        | 'ida'
        | 'left'
        | 'lefthanded'
        | 'massage'
        | 'pingala'
        | 'raise'
        | 'right'
        | 'righthanded'
        | 'rising'
        | 'silent'
        | 'superego'
        | 'tapping'
      )[]
    | null;
  duration?: number | null;
  /**
   * Auto-generated thumbnail (for videos only)
   */
  thumbnail?: (string | null) | Frame;
  fileMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Admin users bypass all permission restrictions and have complete access to all collections and features.
   */
  admin?: boolean | null;
  /**
   * Granular permissions for specific collections and locales. Adding the same collection multiple times may cause inconsistent behaviour.
   */
  permissions?:
    | {
        /**
         * Select the collection to grant permissions for
         */
        allowedCollection: 'meditations' | 'music' | 'frames' | 'media';
        /**
         * Translate: Can edit localized fields only. Manage: Full create/update/delete access within specified locales.
         */
        level: 'translate' | 'manage';
        /**
         * Select which locales this permission applies to. "All Locales" grants unrestricted locale access.
         */
        locales: ('all' | 'en' | 'cs')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Enable or disable this user
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  /**
   * Client organization or application name
   */
  name: string;
  /**
   * Purpose and usage notes for this client
   */
  notes?: string | null;
  /**
   * Granular permissions for specific collections and locales. Adding the same collection multiple times may cause inconsistent behaviour.
   */
  permissions?:
    | {
        /**
         * Select the collection to grant permissions for
         */
        allowedCollection: 'meditations' | 'music' | 'frames' | 'media';
        /**
         * Translate: Can edit localized fields only. Manage: Full create/update/delete access within specified locales.
         */
        level: 'read' | 'manage';
        /**
         * Select which locales this permission applies to. "All Locales" grants unrestricted locale access.
         */
        locales: ('all' | 'en' | 'cs')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Users who can manage this client
   */
  managers: (string | User)[];
  /**
   * Primary user contact for this client
   */
  primaryContact: string | User;
  /**
   * What domains are associated with this client. Put each domain on a new line.
   */
  domains?: string | null;
  /**
   * Enable or disable API access for this client
   */
  active?: boolean | null;
  /**
   * Timestamp of last API key generation
   */
  keyGeneratedAt?: string | null;
  /**
   * API usage statistics
   */
  usageStats?: {
    /**
     * All-time request count
     */
    totalRequests?: number | null;
    /**
     * Today's request count
     */
    dailyRequests?: number | null;
    /**
     * Maximum historical request count
     */
    maxDailyRequests?: number | null;
    /**
     * Last API call timestamp
     */
    lastRequestAt?: string | null;
    /**
     * Indicates if daily limit exceeded (>1000 requests)
     */
    highUsageAlert?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'resetClientUsage' | 'trackClientUsage';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'resetClientUsage' | 'trackClientUsage') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'meditations';
        value: string | Meditation;
      } | null)
    | ({
        relationTo: 'music';
        value: string | Music;
      } | null)
    | ({
        relationTo: 'frames';
        value: string | Frame;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'narrators';
        value: string | Narrator;
      } | null)
    | ({
        relationTo: 'media-tags';
        value: string | MediaTag;
      } | null)
    | ({
        relationTo: 'meditation-tags';
        value: string | MeditationTag;
      } | null)
    | ({
        relationTo: 'music-tags';
        value: string | MusicTag;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'clients';
        value: string | Client;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'clients';
        value: string | Client;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditations_select".
 */
export interface MeditationsSelect<T extends boolean = true> {
  title?: T;
  locale?: T;
  publishAt?: T;
  slug?: T;
  thumbnail?: T;
  duration?: T;
  narrator?: T;
  tags?: T;
  musicTag?: T;
  frames?: T;
  frameData?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music_select".
 */
export interface MusicSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tags?: T;
  credit?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frames_select".
 */
export interface FramesSelect<T extends boolean = true> {
  preview?: T;
  imageSet?: T;
  category?: T;
  tags?: T;
  duration?: T;
  thumbnail?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tags?: T;
  credit?: T;
  fileMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrators_select".
 */
export interface NarratorsSelect<T extends boolean = true> {
  name?: T;
  gender?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-tags_select".
 */
export interface MediaTagsSelect<T extends boolean = true> {
  name?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meditation-tags_select".
 */
export interface MeditationTagsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  meditations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-tags_select".
 */
export interface MusicTagsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  music?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  admin?: T;
  permissions?:
    | T
    | {
        allowedCollection?: T;
        level?: T;
        locales?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  notes?: T;
  permissions?:
    | T
    | {
        allowedCollection?: T;
        level?: T;
        locales?: T;
        id?: T;
      };
  managers?: T;
  primaryContact?: T;
  domains?: T;
  active?: T;
  keyGeneratedAt?: T;
  usageStats?:
    | T
    | {
        totalRequests?: T;
        dailyRequests?: T;
        maxDailyRequests?: T;
        lastRequestAt?: T;
        highUsageAlert?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskResetClientUsage".
 */
export interface TaskResetClientUsage {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTrackClientUsage".
 */
export interface TaskTrackClientUsage {
  input: {
    clientId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}